### PR TITLE
Bump XBlock version

### PR DESCRIPTION
**Pull request by sanfordstudent**
Reviewer: @jcdyer

### CODE REVIEW

**Comment by jcdyer** [comment]
Looks reasonable.  When they say they're not using the PyPI version because "it moves fast," do they just mean the xblock-utils is trying to track development very closely?

**Comment by sanfordstudent** [comment]
@jcdyer that's how I read it. @bradenmacdonald could you help clarify on Cliff's question above? Thanks!

**Comment by bradenmacdonald** [comment]
@jcdyer @sanfordstudent That comment is three years old - probably no reason to abide by it anymore. Feel free to use PyPI.

**Comment by sanfordstudent** [comment]
Upon rereading the comment, I _think_ what it's trying to say is that the **XBlock** repo is the thing that's not in PyPI, so we pull it down here. Does that make sense?

**Comment by bradenmacdonald** [comment]
Yep, that was my understanding.

**Comment by jcdyer** [comment]
Cool.  Then lets update it to use `XBlock>=0.5.0` straight from pypi

**Comment by sanfordstudent** [comment]
Well, the errors now match what I see when I run the drag and drop integration tests locally, which is... useful? Maybe? When I run the xblock-utils tests locally they all pass, so I don't really know how to proceed here.

**Comment by bradenmacdonald** [comment]
@sanfordstudent Maybe ask the testeng folks. Looks like some sort of issue with bok choy and/or Selenium (both of which are being used here).

**Pull request closed without merging**
