### PR TITLE
Release

### PR DESCRIPTION
**Pull request by antoviaque**
@douglashall This is the current diff that would need to get upstream review, if you want to pull in the changes from master (otherwise just cherry-pick your change into the edx-release branch, we'll take care of this).

### CODE REVIEW

**Comment by douglashall** [comment]
@antoviaque I opted to cherry-pick my changes into the edx-release branch.

**Comment by antoviaque** [comment]
@douglashall Yup, that makes sense - thank you!

**Comment by bradenmacdonald** [comment]
@antoviaque Can you close this PR?

**Comment by antoviaque** [comment]
@bradenmacdonald Sure

**Pull request closed without merging**
