### PR TITLE
add I18n support to js templates

### PR DESCRIPTION
**Pull request by msaqib52**
This PR adds I18n support for js templates.

@shafqatfarhan can you review this?

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @msaqib52! I've created [OSPR-5245](https://openedx.atlassian.net/browse/OSPR-5245) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@msaqib52 Thank you for your contribution. Let me try to find someone to review it.

**Review by hasnain-naveed — APPROVED** [review]
Looks good to me and I would recommend getting another review from code owners 👍

**Review by sarina — APPROVED** [review]

**Comment by edx-webhook** [comment]
@msaqib52 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-utils&entry.867055334=https://github.com/edx/xblock-utils/pull/124&entry.1484655318=https://github.com/msaqib52&entry.752974735=2020-11-24+09:02&entry.1917517419=2020-12-02+17:24&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by msaqib52** [comment]
@sarina Thank you for merging the PR. Could you please also create the release for this PR(v 2.1.2)

**Comment by natabene** [comment]
@msaqib52 Sorry, I understand what you mean by this.

**Pull request merged**
