### PR TITLE
Update xblock-utils version in setup.py

### PR DESCRIPTION
**Pull request by itsjeyd**

### CODE REVIEW

**Comment by nedbat** [comment]
I hate to keep being picky, but I think you will need to make this 1.0.2, since the 1.0.1 tag has already been used.

**Comment by itsjeyd** [comment]
@nedbat I could do that, or I could remove the 1.0.1 tag and recreate it. What would you prefer?

**Comment by bradenmacdonald** [comment]
@itsjeyd I think you will have to create a new version number and a new tag. It's possible to move git tags around, but I think it could causes conflicts for anyone who happened to fetch/pull down the tags before they were moved.

@nedbat Thanks for your patience and help with this. We're used to just pushing hash updates, and haven't had as much experience with version tags.

**Comment by itsjeyd** [comment]
@bradenmacdonald OK, I updated the version number in setup.py to 1.0.2. I'll create and push a new tag to edx:master once this PR merges.

**Comment by bradenmacdonald** [comment]
LGTM :+1:

**Comment by nedbat** [comment]
:+1:

**Pull request merged**
