### PR TITLE
 Introduce XBlock resource templates

### PR DESCRIPTION
**Pull request by ahmedaljazzar**
NOTE: This PR is based on #52 just for internal testing purposes at Open Craft. Until the internal testing passes you can check the last commit for the changes.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ahmedaljazzar! I've created [OSPR-2855](https://openedx.atlassian.net/browse/OSPR-2855) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@ahmedaljazzar Just to be clear, you don't want us to review this, correct?

**Comment by ahmedaljazzar** [comment]
@natabene I'm currently waiting for an internal review to take place first. Pinging @bradenmacdonald and @smarnach from OpenCraft here.

**Comment by bradenmacdonald** [comment]
@ahmedaljazzar I don't think @smarnach or I knew about this PR. Can you please change the target branch to `open-craft:jazzar/editor-tabs` instead of `master`, and then it will be much easier to review.

**Comment by edx-webhook** [comment]
@ahmedaljazzar Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-utils&entry.867055334=https://github.com/edx/xblock-utils/pull/53&entry.1484655318=https://github.com/ahmedaljazzar&entry.752974735=2018-11-29+06:25&entry.1917517419=2018-12-07+08:57&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
