### PR TITLE
Fix: Make sure EDIT dialog for block fields always operates on up-to-date data

### PR DESCRIPTION
**Pull request by itsjeyd**
The changes in this PR address the following problem:

If a field name is shared across different types of blocks, the associated value is copied from one block to another when doing the following:

1. Bring up EDIT dialog for one of the blocks and click "Save" (with or without changing the value of the field that share a name with fields defined on other types of blocks).
2. Bring up EDIT dialog for another type of block and click "Save" without changing the value of the field that shares a name with a field belonging to the previously edited block.

**Note** that the problem only occurs if the field of the first block is set up to be edited using TinyMCE.

**Testing**

1. Enable `"step-builder"` for a course in Studio.
2. Add a Step Builder block to a unit.
3. Add a Mentoring Step to the Step Builder block.
4. Add an MCQ to the Mentoring Step.
5. Add two choice blocks (with valid choice texts) to the MCQ, and specify which choices are correct.
6. Add a tip block and a review message block to the MCQ.
7. Edit the contents of the review message block and click "Save".
8. For each of the remaining blocks, click "EDIT" and then "Save" without making changes. Observe that choice texts and tip contents are *not* replaced with the contents of the review message.

### CODE REVIEW

**Comment by Kelketek** [comment]
@itsjeyd This works for me. Is there any way a test can be written for it?

**Comment by edx-webhook** [comment]
Thanks for the pull request, @itsjeyd! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=29&repo=edx%2Fxblock-utils

**Comment by itsjeyd** [comment]
@Kelketek I'm not sure. AFAICT writing a test would involve making TinyMCE available in the workbench runtime, and then finding a way to assert that `remove` is called when saving or canceling an edit. I looked into that and found that it is possible to inject a fake `$.fn.tinymce` function into the page from an integration test. However, there doesn't seem to be a way to do this *before* the code in studio_edit.js runs. As a result, the code will assume that TinyMCE is not available, and will not execute any TinyMCE-related logic (so any logic for checking that `remove` was called would fail).

**Comment by Kelketek** [comment]
Alright, then. :+1:

**Pull request merged**
